- name: configuring rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: copying the repo details 
    ansible.builtin.copy:
      src: rabitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: installing rabbitmq server
    ansible.builtin.command: rabbitmq-server -y

  - name:  start rabbitmq server and enable
    ansible.builtin.service:
      name: rabbitmq-server
      state: started 
      enabled: yes

  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions: 
      - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present
        