- name: configuring user component
  hosts: user
  become: yes 
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present 

  - name: creating a app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: creating roboshop system user
    ansible.builtin.user:
      user: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download user component
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: extract the code 
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy user service to system directory
    ansible.builtin.copy:
      src: user.service 
      dest: /etc/systemd/system/user.service

  - name: reload the system user 
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      enabled: yes
      name: user
      state: started
      